FROM golang:alpine

ENV GOPATH /go/libs:/go

RUN apk add --no-cache git
RUN go get github.com/go-chi/chi && \
    go get github.com/gorilla/websocket

EXPOSE 8001

CMD ["go", "run", "cmd/server/main.go", "-dev"]
